config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admins
  devise_for :users
  resources :articles do
  	 get :autocomplete_tag_name, :on => :collection
  	end
  root 'articles#index'
  post 'articles/index'
  get 'tags/:tag', to: 'articles#index', as: :tag
  get '*path' => redirect('/')
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :recoverable,  :trackable, :registerable, :validatable

  has_many :articles
  
end

app/models/article.rb
class Article < ActiveRecord::Base


	belongs_to :user
	belongs_to :category

	extend FriendlyId
	friendly_id :title, use: :slugged

	acts_as_taggable_on :tags

	def tag_list
  		self.tags.map { |t| t.name }.join(", ")
	end

	def tag_list=(new_value)
	  tag_names = new_value.split(/\s*,\s*+/)
	  self.tags = tag_names.map { |name| Tag.where('name = ?', name).first or Tag.create(:name => name) }
	end

	is_impressionable :counter_cache => true

end

app/models/category.rb
class Category < ActiveRecord::Base

	has_many :articles
	
end

app/models/tag.rb
class Tag < ActsAsTaggableOn::Tag
end

app/models/tagging.rb
class Tagging < ActsAsTaggableOn::Tagging
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	skip_before_filter :verify_authenticity_token 
	before_action :find_article, only: [:show, :edit, :update, :destroy]
	autocomplete :tag, :name

	def index
		@sort = params[:sort]
		if params[:category].blank? and params[:tag].blank?
			if @sort == 'recent'
				@articles = Article.all.order("created_at DESC").paginate(page: params[:page], per_page: 6)
			elsif @sort == 'recent'
				@articles = Article.all.order("impressions_count DESC").paginate(page: params[:page], per_page: 6)
			elsif @sort == 'alpha'
				@articles = Article.all.order("title").paginate(page: params[:page], per_page: 6)
			else
				@articles = Article.all.order("created_at DESC").paginate(page: params[:page], per_page: 6)
			end
		elsif !params[:category].blank?
			@category_id = Category.find_by(name: params[:category]).id
			@articles = Article.where(category_id: @category_id).order("created_at DESC").paginate(page: params[:page], per_page: 15)
		elsif params[:tag]
			@articles = Article.all.tagged_with(params[:tag]).order("created_at DESC").paginate(page: params[:page], per_page: 15)
		end
	end

	def show
		impressionist(@article)		
	end

	def new
		@article = current_admin.articles.build
	end

	def create
		@article = current_admin.articles.build(article_params)
		if @article.save
			redirect_to @article
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @article.update(article_params)
			redirect_to @article
		else
			render 'edit'
		end
	end

	def destroy
		@article.destroy
		redirect_to root_path
	end

	private

	def find_article
		@article = Article.friendly.find(params[:id])
	end

	def article_params
		params.require(:article).permit(:title, :tag_list, :content, :category_id, :slug)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

	class HTMLwithPygments < Redcarpet::Render::HTML
		def block_code(code,language)
			Pygments.highlight(code, lexer: language)
		end
	end

	def markdown(content)
		renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
		options = {
			autolink: true,
			no_intra_emphasis: true,
			disable_indented_code_blocks: true,
			fenced_code_blocks: true,
			lax_html_blocks: true,
			strikethrough: true,
			superscript: true
		}
		Redcarpet::Markdown.new(renderer, options).render(content).html_safe
	end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_disqus.html.erb
<div id="disqus_thread"></div>
<script>

var disqus_config = function () {
this.shortname = 'webarchwiki'
this.page.url = '<%= url_for([@article, {only_path: false}]) %>'; // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = '<%= @article.id %>'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
this.page.title = '<%= @article.title %>';
};

(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');

s.src = '//webarchwiki.disqus.com/embed.js';

s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/articles/_form.html.erb
<%= simple_form_for @article do |f| %>
	
	<% if @article.errors.any? %>
		<h2><%= pluralize(@article.errors.count, "error") %> prevented this article from  saving</h2>
		<ul>
			<% @article.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	<% end %>

	<%= f.collection_select :category_id, Category.all, :id, :name, {prompt: "Choose a category"} %>
	<br><br>

	<%= f.label :title %><br>
	<%= f.text_field :title %>
	
	<br>
	<br>

	<%= f.label :tag_list %><br>
	<%= f.autocomplete_field :tag_list, autocomplete_tag_name_articles_path, :"data-delimiter" => ', ' %> 
	
	<br>
	<br>

	<%= f.label :content, "Write article here" %><br>
	<%= f.text_area :content %>
	
	<br>
	<br>

	<%= f.submit %>

<% end %>
	

app/views/articles/edit.html.erb
<h1 id="page_title">Edit Article</h>

<div class="skinny_wrapper wrapper_padding">
	<%= render 'form' %>
	<br><br>
	
	<%= link_to "Back", root_path, class: "button"%>
	
</div>

app/views/articles/index.html.erb
<div id="banner">
	<h1>Collaboration is the strategy.</h1>
</div>

<div id="articles_wrapper" class="skinny_wrapper">
<form method='post' action='/articles/index' >
	<span class="custom-dropdown big">
		<select name="sort" id="sort" onchange='this.form.submit()'>
		  <option value="recent">Most Recent</option>
		  <option value="views">Most Viewed</option>
		  <option value="alpha">Alphabetically</option>
		</select>
	</span>
</form>
<br><br><br>

<% @articles.each do |article| %>
	<div class="article">
			<p class="date">Published: <%= article.created_at.strftime('%d %b, %Y') %></p>
			<h2><%= link_to article.title, article %></h2>
			<p class="date"><b>Tags:</b> <%= raw article.tag_list %></p>
			<hr>
		</div>
		<% end %>
		
</div>

<!-- For pagination -->
<%= will_paginate @articles %>		

<div id="tag_cloud" class="skinny_wrapper">

<ul class="tags">
	<% tag_cloud Article.tag_counts, %w[s m l] do |tag, css_class| %>
	<li><%= link_to tag.name, tag_path(tag.name), class: css_class %></li>
	<% end %>
	</ul> 
</div>

<!-- <ul>
	<li><%= link_to "All Articles", root_path%></li>
<% Category.all.each do |category| %>
			<li><%= link_to category.name, articles_path(category: category.name) %></li>
			
		<% end %>
</ul>	 -->

app/views/articles/new.html.erb
<h1 id="page_title">New Article</h>

<div class="skinny_wrapper wrapper_padding">
	<%= render 'form' %>
	<br><br>
	<%= link_to "Back", root_path, class: "button"%>

</div>

app/views/articles/show.html.erb
<div id="article_show_content" class="skinny_wrapper wrapper_padding">
	<header>
		<p class="date"><%= @article.created_at.strftime('%d %b, %Y') %></p>
		<h1><%= @article.title %></h1>
		<hr>
	</header>
		
	<div id="content">	
		<%=markdown @article.content %>
	</div>
	
	<div id="admin_links">
		<%= link_to "Back", root_path %>
		<% if signed_in? %>
			<%= link_to "Edit", edit_article_path %>
		<% end %>
		<% if admin_signed_in? %>
				<% if current_admin.email == 'sarang.sharma14@gmail.com' %>
					<%= link_to "Delete", article_path(@article), method: :delete, data: { confirm: "Are you sure? "} %>
				<% end %>
		<% end %>
	</div>	

	<hr>

		<div id="share_box">
			<p>Share <%= @article.title %></p>
			<a onclick="javascript:window.open('http://twitter.com/share?text=<%= @article.title %>&amp;url=<%= url_for([@article, {only_path: false}]) %>', '_blank', 'width=800,height=500, top=200,left=300');viod(0); ">
			<i class="fa fa-twitter"></i></a>
			<a onclick="javascript:window.open('http://www.facebook.com/sharer.php?u=<%= url_for([@article, {only_path: false}]) %>', '_blank', 'width=800,height=500, top=200,left=300');viod(0); ">
			<i class="fa fa-facebook"></i></a>
			<a onclick="javascript:window.open('http://plus.google.com/share?url=<%= url_for([@article, {only_path: false}]) %>', '_blank', 'width=800,height=500, top=200,left=300');viod(0); ">
			<i class="fa fa-google-plus"></i></a>
		</div>

	<hr>
	


		<%= render 'disqus' %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WebarchWiki</title>
  <link href='//fonts.googleapis.com/css?family=Raleway:400,700' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header id="main_navigation" class="clearfix">
	<%= link_to "WebarchWiki", root_path, class: "name" %>
	<nav>
	<% if admin_signed_in? %>
		<%= link_to "New Article", new_article_path %>
	<% end %>

	<% if !(signed_in?) %>
		<%= link_to "Log In", new_user_session_path%>
		<%= link_to "Sign Up", new_user_registration_path %>
		<% end %>
	<% if user_signed_in? %>
				<%= link_to "My Account", edit_user_registration_path %>
				<%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
			<% end %>
	<% if admin_signed_in? %>
				<%= link_to "Admin Account", edit_admin_registration_path %>
				<%= link_to "Sign Out", destroy_admin_session_path, method: :delete %>
			<% end %>
			</nav>
</header>

<% if notice %>
	<p class="notice"><%= notice %></p>
<% elsif alert %>
	<p class="alert"><%= alert %></p>
<% end %>

<div id="main">

<%= yield %>

</div>
<footer id="main_footer">
		<p class="copyright">&copy;Webarch</p>
		<nav>
			<a href="https://www.facebook.com/wEBARChclub" target="_blank"><i class="fa fa-facebook fa-2x"></i></a>
			<a href="https://www.youtube.com/channel/UCiDFs4udzbnGkwypt1-c3tA/feed"><i class="fa fa-youtube-play fa-2x" target="_blank"></i></a>
		<nav>
	</footer>

</body>
</html>